const Global = {
  Failed: 0,
  OK: 1,
  OTP: 2,
  DECIMAL_MODE_CONSTANT: 10000,
  Success: "Success",
  LOG_SUCCESS: "Log created successfully.",
  REQUIRED_FIELD_MISSING: "Required field is missing.",
  BROADCAST_REQUIRED: "Broadcast balance must be greater than 0.",
  PLEASE_DO_NOT_CHANGE_IT_OFFICIAL_USE: "PLEASEDONOTCHANGEITOFFICIALUSE",
  REQUIRED_FIELDS_MISSING: "Required fields are missing.",
  REGISTER_SUCCESS: "Registered successfully.",
  SOMETHING_WENT_WRONG: "Something went wrong.",
  INVALID_ID_PWD: "Email and password does not match.",
  INVALID_PWD: "Password does not match.",
  NO_ACCOUNT_FOUND: "Account not found.",
  NO_ACCOUNT_REGISTERED: "Email id is not registered with us.",
  USER_NOT_FOUND: "User not found.",
  NO_USER_FOUND: "User not found.",
  EMAIL_ALREADY_EXISTS: "E-mail address already exists.",
  PREFERENCES_UPDATED_SUCCESS: "Preferences updated successfully.",
  PASSWORD_UPDATE_SUCCESS: "Password changed successfully.",
  COMMUNICATION_UPDATE_SUCCESS:
    "Communication information updated successfully.",
  USER_UPDATED_SUCCESS: "User details updated successfully.",
  LABELS_UPDATED_SUCCESS: "Vip labels updated successfully.",
  RAKEBACK_UPDATED_SUCCESS: "Rackback percent updated successfully.",
  USER_STATUS_UPDATED_SUCCESS: "User status updated successfully.",
  DISTRIBUTION_UPDATED_SUCCESS: "Distribution data updated successfully.",
  USER_LOGGED_IN_SUCCESS: "User logged in successfully.",
  UNAUTHORIZED: "User disabled by admin",
  FP_LINK_SENT_SUCC:
    "A link has been sent to your email to reset your password.",
  FP_LINK_INVALID: "The link used for forgot password is Expired.",
  PSWD_UPDATED_SUCC: "Password updated successfully.",
  PSWD_UPDATED_FAILED: "Password updated failed.",
  USER_NOT_ACTIVE: "Account is inactive  by admin", //"User not active.",
  VERIFICATION_CODE: "Verification Code",
  VERIFICATION_CODE_SENT_SUCC:
    "A verification code has been sent to your email.",
  INCORRECT_VERIFICATION_CODE: "Two factor code is incorrect.",
  SECRET_GENERATED_SUCCESSFULLY: "Two factor enable successfully.",
  SECRET_GENERATED_FAILED: "Two factor generation failed.",
  SECRET_DISABLED_SUCCESSFULLY: "Two factor is disabled successfully.",
  EVEON_ADDED_SUCCESSFULLY: "Eveon added successfully.",
  TIP_SENT_SUCCESSFULLY: "Tip sent successfully.",
  TIP_SHOULD_GREATER_THEN_ZERO: "Tip amount should be greater than 0.",
  AMOUNT_SHOULD_GREATER_THEN_ZERO: "Amount should be greater than 0.",
  User_SHOULD_GREATER_THEN_ZERO: "User must be greater than 0.",
  IGNORE_SELF: "Cannot ignore self.",
  SECRET_DISABLED_FAILED: "Secret disabling failed.",
  OLD_PASSWORD_NOT_CORRECT: "Old password is not correct",
  NOT_FOUND: "No data found matching the criteria.",
  BALANCE_NOT_SUFFICIENT: "Insufficient balance.",
  BALANCE_REFRESHED: "Balance is refreshed.",
  SEED_NOT_FOUND: "Server Seed not found.",
  SEED_UNHASH_FAILED: "Failed to unhash due to active server seed.",
  BET_PLACED: "Bet placed successfully.",
  BET_NOT_FOUND: "Bet not found.",
  INVALID_BET: "Bet data not valid.",
  USER_REMOVED: "User removed successfully.",
  EVEON_ALREADY_CLAIMED: "Eveon already claimed, Please try after some time.",
  Friend_req: "Friend request sent successfully.",
  Already_Friend_Sent: "Already send a friend request.",
  Already_Friend: "Already a friend.",
  IGNORE_FAILED: "Ignoring user failed. Please try after sometime",
  ALREADY_IGNORE: "User already ignored",
  EMAIL_VERIFIED: "Email verified successfully.",
  UNFRIEND_SUCCESS: "Friend removed successfully",
  EMAIL_VERIFIED_FAILED: "Email verification failed.",
  INVALID_VERIFICATION_CODE: "Invalid verification",
  FRIEND_REQUEST_BLOCKED:
    "You cannot sent request, user has blocked friend requests.",
  MESSAGE_PRIVACY_ENABLED: "This user has enabled privacy.",
  DISTRIBUTION_AMOUNT_UPDATED_SUCCESS:
    "Distribution amount updated successfully.",
  MASTER_CURRENCY_UPDATED_SUCCESS: "Maxbet amount updated successfully.",
  TOKEN_MISSING: "No token provided.",
  TOKEN_AUTHENTICATION_FAILED: "Failed to authenticate token.",
  MOBILE_ALREADY_EXISTS: "Mobile no already exist.",
  USER_DISABLED: "User disabled by admin. ",
  USERNAME_ALREADY_EXISTS: "User name already exists.",
  INVALID_PWD: "password does not match.",
  REMOVE_FRIEND_REQUEST: "Friend request remove successfully.",
  Disabled_USER: "You are disabled by admin.",
  UNCONFIRMED_UTXOS:
    "Address contains unconfirmed transaction. Please try again later.",
  PROCESSING_TRANSACTION:
    "Your request is being processed. On completion, you will receive an email conveying your transaction status.",
  INSUFFICIENT_ADMIN_BAL: "Insufficient balance in admin account.",
  AFFILIATE_PROGRAM: "Affiliate program updated successfully.",
  WITHDRAW_SUCCESSFUL: "Commission withdrawn successfully.",
  NO_COMMISSION_FOUND: "No Commission to be withdrawn.",
  AMOUNT_SHOULD_GREATER_THAN_0: "Amount should be greater than 0",
  AMOUNT_SHOULD_BE_GREATER_THAN_MIN:
    "Amount should be greater than specified minimum withdraw amount of currency",
  AMOUNT_SHOULD_BE_GREATER_THAN_MIN_TIP:
    "Amount should be greater than minimum tip amount",
  ADMIN_MESSAGE_SUCCESFUL: "Message sent successfully",
  COLOR_ASSIGN_SUCCESFUL: "Color assign successfully",
  // Chat
  USERNAME_UPDATED: "Name updated successfully",
  NICKNAME_IN_USE: "Nickname is already in use",
  USER_NOT_IGNORED: "User not in ignored list",

  // Message for email subject ....
  SUBJ_USER_REGITERS_SUCCESS: "Welcome to Eveon Coin",
  SUBJ_USER_FORGOT_PASSWORD: "Password Reset Request for ", //"Eveon Coin : Forgot Password",
  SUBJ_USER_DEPOSIT: "Eveon Coin : Deposit",
  SUBJ_USER_WITHDRAW: "Eveon Coin : Withdraw",
  SUBJ_USER_WITHDRAW_FAILED: "Eveon Coin : Withdraw Failed",
  SUBJ_ADMIN_DEPOSIT: "Eveon Coin : New request for deposit",
  SUBJ_WITHDRAW_APPROVED: "Eveon Coin : Withdrawal Approved",
  SUBJ_WITHDRAW_DECLINED: "Eveon Coin : Withdrawal Declined",
  SUBJ_ADMIN_WITHDRAW_FAILED: "Eveon Coin :Failed withdraw",
  SUBJ_ADMIN_WITHDRAW: "Eveon Coin :New request for withdraw",
  ADMIN_MAIL_ID: "admin@mailinator.com",
  APPRECIARION_MAIL: "Congratulation ",

  // Withdraw
  TRANSACTION_SUCCESS: "Transaction successful",
  TRANSACTION_FAILED: "Transaction failed",
  TRANSACTION_DECLINED_SUCCESS: "Transaction declined successfully",
  TRANSACTION_DECLINED_FAILED: "Transaction decline failed",
  TRANSACTION_APPROVED_SUCCESS: "Transaction approved successfully",
  TRANSACTION_APPROVED_FAILED: "Transaction approval failed",
  TRANSACTION_APPROVED_BY_ADMIN: "Transaction approved by admin",
  TRANSACTION_DECLINED_BY_ADMIN: "Transaction declined by admin",
  NO_PENDING_TRANSACTION: "Operation failed, No pending transaction found",

  //Coinflip
  COINFLIP_SUCCESSFUL: "Coinflip is matched successfully",
  COINFLIP_CANNOT_MATCHED: "Coinflip cannot be matched",
  COINFLIP_RECORDED: "Your Coinflip is recorded successfully",
  COINFLIP_SIDE_ERROR: "Coinflip side must be either heads or tails",
  COINFLIP_LIMIT_REACHED: "Coinflip limit reached for this currency",
  REMOVE_COINFLIP: "Your Coinflip is removed successfully",
  TOGGLE_COINFLIP: "Your Coinflip is toggled successfully",
  CHAT_ICON_SUCCESS: "Chat Icon updated successfully",
  ICON_CLAIM_SUCCESS: "Chat Icon claimed successfully",
  ALREADY_CLAIMED: "Icon already claimed.",

  // Rain
  FAILED_SEND_RAIN: "Something went wrong, Please try again",
  RAIN_SENT_SUCCESSFULLY: "Rain sent successfully.",
  MEGARAIN_SENT_SUCCESSFULLY: "Megarain Sent successfully.",
  MIN_MEGARAIN_AMOUNT: "MegaRain amount must be greater than or equal to ",
  NUMBER_OF_USERS_ERROR:
    "Number of users must be less than maximum number of users allowed.",
  NO_MATCHING_USER: "User not found matching the criteria.",
  RAKEBACK_CLAIMED_SUCCESS: "Rakeback claimed successfully",
  RAKEBACK_ALREADY_CLAIMED: "Rakeback already claimed",

  // chat command
  WARN_SUCCESS: "User warned successfully.",
  WARN_FAILED: "User warning failed.",
  TIMEOUT_SUCCESS: "User timed out successfully.",
  TIMEOUT_FAILED: "User time out failed.",
  MUTE_SUCCESS: "User muted successfully.",
  MUTE_FAILED: "Muting user failed.",
  BAN_SUCCESS: "User baned successfully.",
  BAN_FAILED: "Ban user failed.",
  UNBAN_SUCCESS: "User unbaned successfully.",
  UNBAN_FAILED: "Unbaned user failed.",
  CHAT_ALLOWED: "CHAT_ALLOWED",
  CHAT_NOT_ALLOWED: "CHAT_NOT_ALLOWED",
};
module.exports = Global;
